### ISSUE TITLE
[Feature] Remove redis dependency

### ISSUE THREAD

**Issue by prathameshmorefynd** [fynd-platform/GA4-Extension#16]
### Is this a request for a new feature or an enhancement to an existing one?

Enhancement/Optimization/Refactor

### Feature/Enhancement Name

Remove redis dependency

### Summary

Remove redis dependency

### Motivation

Remove the dependency on Redis and use MongoDB to store tokens instead.

### Detailed Description

Remove the dependency on Redis and use MongoDB to store tokens instead.

### Does this request involve a breaking change?

No

**Comment by rbgpt** [comment]
This issue is fixed. Closing.
